# for postgres services
version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employee_db_development
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
